@@include('components/function.js')
@@include('components/dynamic_adapt.js')
@@include('components/accordion.js')
@@include('components/rating.js')
@@include('components/countdown.js')
@@include('components/colors.js')